table attrition_by_dimension
	lineageTag: c4b072ed-aec2-4bbe-bbca-dd2a9b590fd9

	column dimension
		dataType: string
		lineageTag: b85c2110-b1d5-4001-a2c5-46dd68acb5f7
		summarizeBy: none
		sourceColumn: dimension

	column category
		dataType: string
		lineageTag: b7d7e974-c4f1-46b9-8554-ab318563e5ba
		summarizeBy: none
		sourceColumn: category

	column sort_key
		dataType: string
		lineageTag: 7b0fc5c8-bc9d-4200-831c-6722adda2f19
		summarizeBy: none
		sourceColumn: sort_key

	column headcount_ever
		dataType: int64
		formatString: 0
		lineageTag: a82471c9-a506-4022-865a-d9cc2aedaa44
		summarizeBy: sum
		sourceColumn: headcount_ever

	column active_headcount
		dataType: int64
		formatString: 0
		lineageTag: 3ea5ba37-7cf3-4440-b2f1-bf5dd982aac6
		summarizeBy: sum
		sourceColumn: active_headcount

	column terminations
		dataType: int64
		formatString: 0
		lineageTag: d2353947-71ab-41cc-bcfd-a3ac1ba82865
		summarizeBy: sum
		sourceColumn: terminations

	column voluntary_terms
		dataType: int64
		formatString: 0
		lineageTag: 32bffe8c-57f9-4af7-a243-ce0d8d1cd780
		summarizeBy: sum
		sourceColumn: voluntary_terms

	column attrition_rate
		dataType: double
		lineageTag: a1c3e730-56fd-43a8-8f78-7ea7402cc7c6
		summarizeBy: none
		sourceColumn: attrition_rate

	column voluntary_share
		dataType: double
		lineageTag: bf7b153a-dfc5-4805-9261-71db0a28ba7b
		summarizeBy: none
		sourceColumn: voluntary_share

	column pct_of_dimension_exits
		dataType: double
		lineageTag: 4ddf858a-c843-4835-aee2-17d74b3f1567
		summarizeBy: none
		sourceColumn: pct_of_dimension_exits

	column attrition_rank
		dataType: int64
		formatString: 0
		lineageTag: 91089e50-5b4c-417e-80e4-b9709e0f236b
		summarizeBy: none
		sourceColumn: attrition_rank

	partition attrition_by_dimension = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\attrition_by_dimension.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"dimension", type text}, {"category", type text}, {"sort_key", type text}, {"headcount_ever", Int64.Type}, {"active_headcount", Int64.Type}, {"terminations", Int64.Type}, {"voluntary_terms", Int64.Type}, {"attrition_rate", type number}, {"voluntary_share", type number}, {"pct_of_dimension_exits", type number}, {"attrition_rank", Int64.Type}})
				in
				    Typed
