table attrition_by_dimension
	lineageTag: 6be50cb6-488e-4d21-9aa7-0d235a50895e

	column dimension
		dataType: string
		lineageTag: 7d43b000-c218-4446-b1a2-054c3a466ddc
		summarizeBy: none
		sourceColumn: dimension

	column category
		dataType: string
		lineageTag: 3af8c0dd-2479-4515-846a-a0da81e8d211
		summarizeBy: none
		sourceColumn: category

	column sort_key
		dataType: string
		lineageTag: 892ba4c2-8575-4643-9e02-7b4e4866d940
		summarizeBy: none
		sourceColumn: sort_key

	column headcount_ever
		dataType: int64
		formatString: 0
		lineageTag: 67741dfb-1b20-4d08-96cd-97bf67abb25d
		summarizeBy: sum
		sourceColumn: headcount_ever

	column active_headcount
		dataType: int64
		formatString: 0
		lineageTag: 90ce8271-6cb2-4d96-a6a4-021c8ea41c81
		summarizeBy: sum
		sourceColumn: active_headcount

	column terminations
		dataType: int64
		formatString: 0
		lineageTag: 7a52144b-1293-4c62-ac0a-8ffa870c168b
		summarizeBy: sum
		sourceColumn: terminations

	column voluntary_terms
		dataType: int64
		formatString: 0
		lineageTag: e4be35f5-0c00-4771-92fc-49564a4b0fd4
		summarizeBy: sum
		sourceColumn: voluntary_terms

	column attrition_rate
		dataType: double
		formatString: 0.0%
		lineageTag: 369e2fc4-c49c-4f5c-9437-c30e44cbb980
		summarizeBy: none
		sourceColumn: attrition_rate

	column voluntary_share
		dataType: double
		formatString: 0.0%
		lineageTag: 18d8b9d6-f0ff-4cbd-9a52-8468ae7fdaf4
		summarizeBy: none
		sourceColumn: voluntary_share

	column pct_of_dimension_exits
		dataType: double
		formatString: 0.0%
		lineageTag: 7e706c47-2787-4880-beaf-aff8df4c9900
		summarizeBy: none
		sourceColumn: pct_of_dimension_exits

	column attrition_rank
		dataType: int64
		formatString: 0
		lineageTag: a790c099-1451-4668-b5bf-8b9f85a29824
		summarizeBy: none
		sourceColumn: attrition_rank

	partition attrition_by_dimension = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\attrition_by_dimension.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"dimension", type text}, {"category", type text}, {"sort_key", type text}, {"headcount_ever", Int64.Type}, {"active_headcount", Int64.Type}, {"terminations", Int64.Type}, {"voluntary_terms", Int64.Type}, {"attrition_rate", type number}, {"voluntary_share", type number}, {"pct_of_dimension_exits", type number}, {"attrition_rank", Int64.Type}})
				in
				    Typed

