table dim_department
	lineageTag: ba14263e-e69e-4383-8dfd-d0e0c6e96fb6

	column department_id
		dataType: int64
		formatString: 0
		lineageTag: 33ff69d4-eee9-4df4-8651-426cf25f8dbc
		summarizeBy: none
		sourceColumn: department_id

	column department
		dataType: string
		lineageTag: f434f438-1668-45cc-8747-e4d1b5489a6f
		summarizeBy: none
		sourceColumn: department

	column division
		dataType: string
		lineageTag: 9a35ef2e-218e-4ac8-a0d7-eb4d5f1fabf1
		summarizeBy: none
		sourceColumn: division

	partition dim_department = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\dim_department.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"department_id", Int64.Type}, {"department", type text}, {"division", type text}})
				in
				    Typed
