table dim_department
	lineageTag: bf5cea24-8df3-4662-bc11-3354d6e34454

	column department_id
		dataType: int64
		formatString: 0
		lineageTag: 9741c449-4f27-4331-b6d6-735313ec4ad4
		summarizeBy: none
		sourceColumn: department_id

	column department
		dataType: string
		lineageTag: 1b6c4bc6-699f-4d9d-8224-2e8eee55dfd0
		summarizeBy: none
		sourceColumn: department

	column division
		dataType: string
		lineageTag: 736a73ff-a946-4a17-95fe-854278720d56
		summarizeBy: none
		sourceColumn: division

	partition dim_department = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\dim_department.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"department_id", Int64.Type}, {"department", type text}, {"division", type text}})
				in
				    Typed

