table dim_location
	lineageTag: 0ecba40b-fd7c-422b-9d35-beaf9a8a9d88

	column location_id
		dataType: int64
		formatString: 0
		lineageTag: 30f7c520-8279-4f81-86ca-dce5802e8798
		summarizeBy: none
		sourceColumn: location_id

	column city
		dataType: string
		lineageTag: b8675a0b-377b-40c1-a03f-feb9dbe21053
		summarizeBy: none
		sourceColumn: city

	column region
		dataType: string
		lineageTag: dbecb939-3afd-4a2d-8db8-96aa4d0534b4
		summarizeBy: none
		sourceColumn: region

	column country
		dataType: string
		lineageTag: ff6c600d-0b6a-4073-8441-fc04193e3498
		summarizeBy: none
		sourceColumn: country

	column is_remote
		dataType: int64
		formatString: 0
		lineageTag: 4b9cb29c-e841-4d2c-b341-22e2b554890c
		summarizeBy: none
		sourceColumn: is_remote

	partition dim_location = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\dim_location.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"location_id", Int64.Type}, {"city", type text}, {"region", type text}, {"country", type text}, {"is_remote", Int64.Type}})
				in
				    Typed
