table dim_job
	lineageTag: f20ee557-2b89-4a43-90b5-8d8a889b1ece

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: b3e27356-e38a-4c68-a84e-218458e352c3
		summarizeBy: none
		sourceColumn: job_id

	column job_title
		dataType: string
		lineageTag: 0de95ca8-29a1-47af-857c-dcfccdc2e341
		summarizeBy: none
		sourceColumn: job_title

	column job_level
		dataType: string
		lineageTag: 948c6188-28bc-48cc-bb6b-3df6618d529e
		summarizeBy: none
		sourceColumn: job_level

	column level_rank
		dataType: int64
		formatString: 0
		lineageTag: cc2ab7b5-e9ee-4dac-a57e-e52f6e24f2c9
		summarizeBy: none
		sourceColumn: level_rank

	column is_management
		dataType: int64
		formatString: 0
		lineageTag: c8102054-89c0-4728-b085-5ea837c69faa
		summarizeBy: none
		sourceColumn: is_management

	partition dim_job = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\dim_job.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"job_id", Int64.Type}, {"job_title", type text}, {"job_level", type text}, {"level_rank", Int64.Type}, {"is_management", Int64.Type}})
				in
				    Typed
