table dim_location
	lineageTag: e2c7e32a-9a2d-42d0-80c7-a98f9616d74b

	column location_id
		dataType: int64
		formatString: 0
		lineageTag: 9757292e-1e83-4d9b-8cbe-87f763d1fc3a
		summarizeBy: none
		sourceColumn: location_id

	column city
		dataType: string
		lineageTag: 9b88f50c-f096-442b-b979-43d41e262a45
		summarizeBy: none
		sourceColumn: city

	column region
		dataType: string
		lineageTag: 5798dce0-6f5f-41de-a2f1-d6fc503d5a39
		summarizeBy: none
		sourceColumn: region

	column country
		dataType: string
		lineageTag: 51c25be5-b7b6-4977-b64c-6ca863c69ebb
		summarizeBy: none
		sourceColumn: country

	column is_remote
		dataType: int64
		formatString: 0
		lineageTag: 074d5d87-50e1-45cc-b750-55120f20e42e
		summarizeBy: none
		sourceColumn: is_remote

	column salary_index
		dataType: double
		formatString: 0.00
		lineageTag: 72640fbf-36ee-5ee4-91f6-fd5be3eb75ad
		summarizeBy: none
		sourceColumn: salary_index

	column attrition_lift
		dataType: double
		isHidden
		formatString: 0.00
		lineageTag: f40191b0-5181-574b-acc7-9de3ba4586d7
		summarizeBy: none
		sourceColumn: attrition_lift

	partition dim_location = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\dim_location.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"location_id", Int64.Type}, {"city", type text}, {"region", type text}, {"country", type text}, {"is_remote", Int64.Type}, {"salary_index", type number}, {"attrition_lift", type number}})
				in
				    Typed

