table dim_job
	lineageTag: cdbaec20-fabe-47d6-bad1-cbf721a50d58

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: 37d019d8-1d18-4164-9172-cd7a4e6492ce
		summarizeBy: none
		sourceColumn: job_id

	column job_title
		dataType: string
		lineageTag: 4f8a4369-0258-46bb-815e-813a22cf4a85
		summarizeBy: none
		sourceColumn: job_title

	column job_level
		dataType: string
		lineageTag: 9abd7c42-7474-4edf-8608-87dd6866905e
		summarizeBy: none
		sourceColumn: job_level

	column level_rank
		dataType: int64
		formatString: 0
		lineageTag: ef552823-0f26-4f12-9683-d6036f73e10c
		summarizeBy: none
		sourceColumn: level_rank

	column is_management
		dataType: int64
		formatString: 0
		lineageTag: 8be98f30-e690-45fa-941e-ae84a4235986
		summarizeBy: none
		sourceColumn: is_management

	partition dim_job = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\dim_job.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"job_id", Int64.Type}, {"job_title", type text}, {"job_level", type text}, {"level_rank", Int64.Type}, {"is_management", Int64.Type}})
				in
				    Typed

