table dim_date
	lineageTag: e4167ab3-972c-459d-adaa-b09abf9d00ab

	column month
		dataType: string
		lineageTag: 83019997-7b5a-42ea-8d22-9e8cff5f55ad
		summarizeBy: none
		sourceColumn: month

	column month_start
		dataType: datetime
		lineageTag: e2eb5b96-c6e2-417e-9249-0e17ddd94c42
		summarizeBy: none
		sourceColumn: month_start

	column year
		dataType: int64
		formatString: 0
		lineageTag: f115c258-7716-46ae-b9e5-f63052aa2243
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: string
		lineageTag: 82e5dfde-2c3c-400c-b127-9a30ee6dc688
		summarizeBy: none
		sourceColumn: quarter

	column month_num
		dataType: int64
		formatString: 0
		lineageTag: ad40cff6-a303-40a2-bf20-d5f0697627ec
		summarizeBy: none
		sourceColumn: month_num

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"month", type text}, {"month_start", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month_num", Int64.Type}})
				in
				    Typed
