table fact_employees
	lineageTag: f58e7ec6-54ce-40a3-a489-8113edc21210

	column employee_id
		dataType: int64
		formatString: 0
		lineageTag: 3c0e1d77-5bc4-40c0-8d03-45d2c30d5985
		summarizeBy: none
		sourceColumn: employee_id

	column employee_name
		dataType: string
		lineageTag: 1bfa190a-1da0-4348-8427-5a0bf3f8fb87
		summarizeBy: none
		sourceColumn: employee_name

	column department_id
		dataType: int64
		formatString: 0
		lineageTag: 59314e97-bdc5-4969-89f6-8fe5f7c1863e
		summarizeBy: none
		sourceColumn: department_id

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: c04f1d0b-886f-42f8-bd63-15a53ee17f07
		summarizeBy: none
		sourceColumn: job_id

	column location_id
		dataType: int64
		formatString: 0
		lineageTag: 14ff6476-c89c-42a4-a86f-7d0d8d2daffe
		summarizeBy: none
		sourceColumn: location_id

	column gender
		dataType: string
		lineageTag: 77c4772e-9063-4ad8-9f1c-2b36957c7459
		summarizeBy: none
		sourceColumn: gender

	column ethnicity_group
		dataType: string
		lineageTag: a75fbdd9-7dbc-4e2a-a973-5f578263406f
		summarizeBy: none
		sourceColumn: ethnicity_group

	column age_band
		dataType: string
		lineageTag: ed5ded43-d5e8-4c7f-9373-92cb3bd61aca
		summarizeBy: none
		sourceColumn: age_band

	column hire_date
		dataType: string
		lineageTag: 7fe476c8-c1b8-4eda-a250-30b08d9754b4
		summarizeBy: none
		sourceColumn: hire_date

	column termination_date
		dataType: string
		lineageTag: 363fd892-ee3b-4c13-b7ab-e86e70fb541b
		summarizeBy: none
		sourceColumn: termination_date

	column term_type
		dataType: string
		lineageTag: 261e6734-03d0-4043-a05e-3c0c81a68e03
		summarizeBy: none
		sourceColumn: term_type

	column is_active
		dataType: int64
		formatString: 0
		lineageTag: 1024f5c2-7b30-490f-b921-17a2943920e1
		summarizeBy: none
		sourceColumn: is_active

	column tenure_months
		dataType: double
		formatString: #,0.0
		lineageTag: 3d900ed9-26d0-40d9-a589-4e6b02eb7dbd
		summarizeBy: none
		sourceColumn: tenure_months

	column base_salary
		dataType: double
		formatString: \$#,0
		lineageTag: 71f0b96a-1295-48b3-8341-6038a2b267aa
		summarizeBy: none
		sourceColumn: base_salary

	column compa_ratio
		dataType: double
		formatString: 0.00
		lineageTag: c0a9323c-83b1-439d-bd60-ce69823a3a5d
		summarizeBy: none
		sourceColumn: compa_ratio

	column performance_rating
		dataType: int64
		formatString: 0
		lineageTag: 5c901179-a343-4bb5-a517-e0abc51f5e74
		summarizeBy: none
		sourceColumn: performance_rating

	column engagement_score
		dataType: double
		formatString: #,0.0
		lineageTag: 97b21938-609d-4c1e-b4f0-293300899e20
		summarizeBy: none
		sourceColumn: engagement_score

	column overtime_hours
		dataType: double
		lineageTag: f3b7bc89-12ee-4117-804a-59e09a2e9a9f
		summarizeBy: none
		sourceColumn: overtime_hours

	column commute_km
		dataType: double
		lineageTag: 8bb7cc6a-77eb-4f0f-a251-e40b1e51a4f7
		summarizeBy: none
		sourceColumn: commute_km

	column months_since_promotion
		dataType: double
		lineageTag: 7eddc511-174a-4a90-b8ec-60ce6588c01c
		summarizeBy: none
		sourceColumn: months_since_promotion

	column manager_id
		dataType: string
		lineageTag: f8c5be50-ea74-4dd3-b82b-246854ff5b87
		summarizeBy: none
		sourceColumn: manager_id

	column tenure_band
		dataType: string
		lineageTag: 108260a3-0757-40bb-af7b-410291274d7f
		summarizeBy: none
		sourceColumn: tenure_band
		sortByColumn: tenure_band_sort

	column tenure_band_sort
		dataType: int64
		formatString: 0
		lineageTag: 4eb1ea09-5c52-41ef-bc12-f05dd29d3173
		summarizeBy: none
		sourceColumn: tenure_band_sort

	partition fact_employees = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\fact_employees.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"employee_id", Int64.Type}, {"employee_name", type text}, {"department_id", Int64.Type}, {"job_id", Int64.Type}, {"location_id", Int64.Type}, {"gender", type text}, {"ethnicity_group", type text}, {"age_band", type text}, {"hire_date", type text}, {"termination_date", type text}, {"term_type", type text}, {"is_active", Int64.Type}, {"tenure_months", type number}, {"base_salary", type number}, {"compa_ratio", type number}, {"performance_rating", Int64.Type}, {"engagement_score", type number}, {"overtime_hours", type number}, {"commute_km", type number}, {"months_since_promotion", type number}, {"manager_id", type text}, {"tenure_band", type text}, {"tenure_band_sort", Int64.Type}})
				in
				    Typed
