table fact_employees
	lineageTag: 9a1b4064-958a-4305-a0d5-6162787914ee

	column employee_id
		dataType: int64
		formatString: 0
		lineageTag: 1dc6d4e6-2976-431d-bdf7-7b6db351b465
		summarizeBy: none
		sourceColumn: employee_id

	column department_id
		dataType: int64
		formatString: 0
		lineageTag: 328431d3-1a18-4c90-9106-c14505a549d5
		summarizeBy: none
		sourceColumn: department_id

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: a01635f5-366f-46bc-adf7-9defe384f415
		summarizeBy: none
		sourceColumn: job_id

	column location_id
		dataType: int64
		formatString: 0
		lineageTag: 415c299e-7016-4d5a-9b4f-595d7c491def
		summarizeBy: none
		sourceColumn: location_id

	column gender
		dataType: string
		lineageTag: 1f847fd5-e2a8-43c4-95b8-a7ee23b49abd
		summarizeBy: none
		sourceColumn: gender

	column ethnicity_group
		dataType: string
		lineageTag: 386cfc16-6af1-496e-bd96-0d65219b0cb1
		summarizeBy: none
		sourceColumn: ethnicity_group

	column age_band
		dataType: string
		lineageTag: f3db449d-64ff-48a8-a6ec-49a1c016acb3
		summarizeBy: none
		sourceColumn: age_band

	column hire_date
		dataType: string
		lineageTag: 4e0aef82-33c0-490d-8589-37d6daceb809
		summarizeBy: none
		sourceColumn: hire_date

	column termination_date
		dataType: string
		lineageTag: 126fab32-fd33-4457-b13b-f30b41cfc741
		summarizeBy: none
		sourceColumn: termination_date

	column term_type
		dataType: string
		lineageTag: 7fb3a2e2-3566-4d83-a125-1d270396ccc3
		summarizeBy: none
		sourceColumn: term_type

	column is_active
		dataType: int64
		formatString: 0
		lineageTag: cbd80609-26c4-4f0d-8eb8-7cf7fd3a41f2
		summarizeBy: none
		sourceColumn: is_active

	column tenure_months
		dataType: double
		lineageTag: 3a7572b5-fda6-4afc-819a-7c78728fc476
		summarizeBy: none
		sourceColumn: tenure_months

	column base_salary
		dataType: double
		lineageTag: 54f2c3b1-8a52-4378-8e43-090fceaf11ab
		summarizeBy: none
		sourceColumn: base_salary

	column compa_ratio
		dataType: double
		lineageTag: 2722f4de-c2d5-4c63-ac7c-b8748ba6ea9c
		summarizeBy: none
		sourceColumn: compa_ratio

	column performance_rating
		dataType: int64
		formatString: 0
		lineageTag: a3450814-1685-4529-a609-1f20e8020767
		summarizeBy: none
		sourceColumn: performance_rating

	column engagement_score
		dataType: double
		lineageTag: 1ad6910f-bc1d-4878-a618-61cf86e5dbbb
		summarizeBy: none
		sourceColumn: engagement_score

	column overtime_hours
		dataType: double
		lineageTag: afbf10df-a73d-4429-b64a-733b06c29244
		summarizeBy: none
		sourceColumn: overtime_hours

	column commute_km
		dataType: double
		lineageTag: a279e145-2288-47d1-b762-4a7fab960535
		summarizeBy: none
		sourceColumn: commute_km

	column months_since_promotion
		dataType: double
		lineageTag: 44bc67fb-b6f9-4202-b19e-3277f41642e0
		summarizeBy: none
		sourceColumn: months_since_promotion

	column manager_id
		dataType: string
		lineageTag: cf29c351-0554-4dbb-8406-c2a9c6f87487
		summarizeBy: none
		sourceColumn: manager_id

	column tenure_band
		dataType: string
		lineageTag: ce2ab88d-fbce-4660-96e8-d8992469b2f5
		summarizeBy: none
		sourceColumn: tenure_band

	partition fact_employees = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\fact_employees.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"employee_id", Int64.Type}, {"department_id", Int64.Type}, {"job_id", Int64.Type}, {"location_id", Int64.Type}, {"gender", type text}, {"ethnicity_group", type text}, {"age_band", type text}, {"hire_date", type text}, {"termination_date", type text}, {"term_type", type text}, {"is_active", Int64.Type}, {"tenure_months", type number}, {"base_salary", type number}, {"compa_ratio", type number}, {"performance_rating", Int64.Type}, {"engagement_score", type number}, {"overtime_hours", type number}, {"commute_km", type number}, {"months_since_promotion", type number}, {"manager_id", type text}, {"tenure_band", type text}})
				in
				    Typed
