table fact_employees
	lineageTag: 41ff2b8e-442a-4798-a6a3-8b9984143ad6

	column employee_id
		dataType: int64
		formatString: 0
		lineageTag: 9bf4fc1a-74f6-4f82-a1c5-7920d10cecf4
		summarizeBy: none
		sourceColumn: employee_id

	column department_id
		dataType: int64
		formatString: 0
		lineageTag: 02488ac7-2ca2-4303-9530-70461b76d48b
		summarizeBy: none
		sourceColumn: department_id

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: a5442323-bfdf-4aa7-b4ff-f4ad2854d08c
		summarizeBy: none
		sourceColumn: job_id

	column location_id
		dataType: int64
		formatString: 0
		lineageTag: 439d871a-d9e1-402a-938b-fbc6376c3e9a
		summarizeBy: none
		sourceColumn: location_id

	column gender
		dataType: string
		lineageTag: 2051b514-aecc-43db-a55f-e98c3eaba397
		summarizeBy: none
		sourceColumn: gender

	column ethnicity_group
		dataType: string
		lineageTag: a0dc24d8-a21a-4660-ad05-73603c5b5ef4
		summarizeBy: none
		sourceColumn: ethnicity_group

	column age_band
		dataType: string
		lineageTag: f63937fa-7ca3-44dc-9eb4-1e239664b0f6
		summarizeBy: none
		sourceColumn: age_band

	column hire_date
		dataType: string
		lineageTag: 7b2e02eb-817c-4d75-8050-b090496b112b
		summarizeBy: none
		sourceColumn: hire_date

	column termination_date
		dataType: string
		lineageTag: b22eaf2d-1f2f-40a2-b288-635a8ae8358c
		summarizeBy: none
		sourceColumn: termination_date

	column term_type
		dataType: string
		lineageTag: 9e2c08b6-3463-4ea5-9369-d7d83a19b13d
		summarizeBy: none
		sourceColumn: term_type

	column is_active
		dataType: int64
		formatString: 0
		lineageTag: d7bc4de3-cef5-4352-a5d1-c4981f28ffb0
		summarizeBy: none
		sourceColumn: is_active

	column tenure_months
		dataType: double
		lineageTag: 36895696-6474-426a-9a43-abdd8256ee73
		summarizeBy: none
		sourceColumn: tenure_months

	column base_salary
		dataType: double
		lineageTag: 52190990-20a2-4c6e-8f2c-b10fec0f5524
		summarizeBy: none
		sourceColumn: base_salary

	column compa_ratio
		dataType: double
		lineageTag: 38e1ad42-abfd-42a1-82d1-2a922485f86b
		summarizeBy: none
		sourceColumn: compa_ratio

	column performance_rating
		dataType: int64
		formatString: 0
		lineageTag: 760aaf7f-e93e-493a-b8c8-affc47c8ec65
		summarizeBy: none
		sourceColumn: performance_rating

	column engagement_score
		dataType: double
		lineageTag: 583ad906-5eb8-40d5-baf3-29c31bca5898
		summarizeBy: none
		sourceColumn: engagement_score

	column overtime_hours
		dataType: double
		lineageTag: 2a8698fc-0e59-4739-9051-a267934d2655
		summarizeBy: none
		sourceColumn: overtime_hours

	column commute_km
		dataType: double
		lineageTag: 70dab233-1d8d-472d-9520-ad577885fa71
		summarizeBy: none
		sourceColumn: commute_km

	column months_since_promotion
		dataType: double
		lineageTag: 4bfdeab9-fd1c-4592-a317-e0ac55b99657
		summarizeBy: none
		sourceColumn: months_since_promotion

	column manager_id
		dataType: string
		lineageTag: 23874309-da53-4464-8655-433b3fdd6fbf
		summarizeBy: none
		sourceColumn: manager_id

	column tenure_band
		dataType: string
		lineageTag: aa3764ab-6a59-496b-8112-dd211d4866d7
		summarizeBy: none
		sourceColumn: tenure_band

	partition fact_employees = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\data\fact_employees.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"employee_id", Int64.Type}, {"department_id", Int64.Type}, {"job_id", Int64.Type}, {"location_id", Int64.Type}, {"gender", type text}, {"ethnicity_group", type text}, {"age_band", type text}, {"hire_date", type text}, {"termination_date", type text}, {"term_type", type text}, {"is_active", Int64.Type}, {"tenure_months", type number}, {"base_salary", type number}, {"compa_ratio", type number}, {"performance_rating", Int64.Type}, {"engagement_score", type number}, {"overtime_hours", type number}, {"commute_km", type number}, {"months_since_promotion", type number}, {"manager_id", type text}, {"tenure_band", type text}})
				in
				    Typed
