table flight_risk_scores
	lineageTag: 1f0fb488-178b-4ffa-a431-85d9e87bdca6

	column employee_id
		dataType: int64
		formatString: 0
		lineageTag: 4b48a4f4-9167-4afd-89d7-335e75d87ee0
		summarizeBy: none
		sourceColumn: employee_id

	column department
		dataType: string
		lineageTag: 0be557ce-e36c-4a8b-8d69-a55fed97abc8
		summarizeBy: none
		sourceColumn: department

	column job_level
		dataType: string
		lineageTag: 0d047190-7ced-4bf9-aa67-5c73d06f1407
		summarizeBy: none
		sourceColumn: job_level

	column region
		dataType: string
		lineageTag: d1ef023c-9756-4114-bfff-06e14460bf6c
		summarizeBy: none
		sourceColumn: region

	column tenure_months
		dataType: double
		lineageTag: 9bb38338-202e-4aa7-8391-161fcec12f22
		summarizeBy: none
		sourceColumn: tenure_months

	column engagement_score
		dataType: double
		lineageTag: 4fd63cc6-e762-4351-96ed-02e0479fb11b
		summarizeBy: none
		sourceColumn: engagement_score

	column risk_score
		dataType: double
		lineageTag: 238b5f55-f68e-4f5d-8af0-da9dc805ec33
		summarizeBy: none
		sourceColumn: risk_score

	column risk_band
		dataType: string
		lineageTag: 1e47d81f-d794-4168-82af-a39788e4ca85
		summarizeBy: none
		sourceColumn: risk_band

	column top_reason
		dataType: string
		lineageTag: b40454a5-aa3f-463d-9050-d1a17db1dda0
		summarizeBy: none
		sourceColumn: top_reason

	partition flight_risk_scores = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\flight_risk_scores.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"employee_id", Int64.Type}, {"department", type text}, {"job_level", type text}, {"region", type text}, {"tenure_months", type number}, {"engagement_score", type number}, {"risk_score", type number}, {"risk_band", type text}, {"top_reason", type text}})
				in
				    Typed
