table funnel_stages
	lineageTag: 669046f0-9cdf-4806-af08-39d29de4970e

	column stage
		dataType: string
		lineageTag: 2ecea7ae-6d4e-4b6f-ade2-033ca2372abd
		summarizeBy: none
		sourceColumn: stage
		sortByColumn: stage_order

	column stage_order
		dataType: int64
		formatString: 0
		lineageTag: 081127dc-f56d-440b-93a8-528ee3d97958
		summarizeBy: none
		sourceColumn: stage_order

	column candidates
		dataType: int64
		formatString: 0
		lineageTag: 82bc8f1c-7ea6-46d3-b427-b2d3ec6f1ffe
		summarizeBy: sum
		sourceColumn: candidates

	column conversion_from_prev
		dataType: double
		formatString: 0.0%
		lineageTag: 9bd84568-5301-4aa8-ad03-81e90a4e15c2
		summarizeBy: none
		sourceColumn: conversion_from_prev

	column overall_conversion
		dataType: double
		formatString: 0.0%
		lineageTag: a26bfb7b-3867-44c9-a579-dd80e3dcc6ce
		summarizeBy: none
		sourceColumn: overall_conversion

	partition funnel_stages = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\funnel_stages.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"stage", type text}, {"stage_order", Int64.Type}, {"candidates", Int64.Type}, {"conversion_from_prev", type number}, {"overall_conversion", type number}})
				in
				    Typed
