table funnel_stages
	lineageTag: b1e65ce0-158b-4839-92d3-26c054fe569f

	column stage
		dataType: string
		lineageTag: c08e74a1-4e49-45b2-bccd-2c9bcec71462
		summarizeBy: none
		sourceColumn: stage
		sortByColumn: stage_order

	column stage_order
		dataType: int64
		formatString: 0
		lineageTag: 58208005-09c1-4d5f-9711-49dec62cb1aa
		summarizeBy: none
		sourceColumn: stage_order

	column candidates
		dataType: int64
		formatString: 0
		lineageTag: 8ac4d118-6ea3-4a53-85b4-0334b0ed5a71
		summarizeBy: sum
		sourceColumn: candidates

	column conversion_from_prev
		dataType: double
		lineageTag: dc2080de-0de6-44f2-b9eb-6da13254d015
		summarizeBy: none
		sourceColumn: conversion_from_prev

	column overall_conversion
		dataType: double
		lineageTag: 115bf69c-9dab-4894-b131-a8c3fd4fbc85
		summarizeBy: none
		sourceColumn: overall_conversion

	partition funnel_stages = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\funnel_stages.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"stage", type text}, {"stage_order", Int64.Type}, {"candidates", Int64.Type}, {"conversion_from_prev", type number}, {"overall_conversion", type number}})
				in
				    Typed
