table headcount_bridge
	lineageTag: 33415a38-ee29-4251-8ce3-5734a8b23fc6

	column bucket
		dataType: string
		lineageTag: 682cfae8-4509-42ae-85f4-a73d799e1a2e
		summarizeBy: none
		sourceColumn: bucket
		sortByColumn: sort_order

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 36c8333b-1a11-43d9-9927-9551ea2aaf9f
		summarizeBy: none
		sourceColumn: sort_order

	column value
		dataType: int64
		formatString: 0
		lineageTag: 14f6330b-0217-43cc-8f7f-b93ebaca4df0
		summarizeBy: sum
		sourceColumn: value

	partition headcount_bridge = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\headcount_bridge.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"bucket", type text}, {"sort_order", Int64.Type}, {"value", Int64.Type}})
				in
				    Typed
