table headcount_bridge
	lineageTag: 3be6c871-93e9-4420-b327-d7143e13567c

	column bucket
		dataType: string
		lineageTag: 50fe1379-41c0-4685-bb30-b0cfb15eb5da
		summarizeBy: none
		sourceColumn: bucket
		sortByColumn: sort_order

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 19ec5657-8074-4fe1-a550-1b5931047585
		summarizeBy: none
		sourceColumn: sort_order

	column value
		dataType: int64
		formatString: 0
		lineageTag: 81707c34-c049-4f69-accb-e131a2c5c735
		summarizeBy: sum
		sourceColumn: value

	partition headcount_bridge = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\headcount_bridge.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"bucket", type text}, {"sort_order", Int64.Type}, {"value", Int64.Type}})
				in
				    Typed

