table headcount_bridge
	lineageTag: 5b6ed1e0-3b6d-4ded-be3c-bb5b36c22009

	column bucket
		dataType: string
		lineageTag: 84baf3f2-f245-4ead-8164-271004f4e7b9
		summarizeBy: none
		sourceColumn: bucket

	column sort_order
		dataType: int64
		formatString: 0
		lineageTag: 343b5e5f-3966-4b26-b3c5-40208ec92a06
		summarizeBy: none
		sourceColumn: sort_order

	column value
		dataType: int64
		formatString: 0
		lineageTag: d632a387-ee69-4619-96ac-7df010c34120
		summarizeBy: sum
		sourceColumn: value

	partition headcount_bridge = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\headcount_bridge.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"bucket", type text}, {"sort_order", Int64.Type}, {"value", Int64.Type}})
				in
				    Typed
