table model_evaluation
	lineageTag: 583bd063-ff8b-49c9-9899-8180a5678c33

	column model
		dataType: string
		lineageTag: 760c9ba3-1cf2-4e08-8267-46516ab91d18
		summarizeBy: none
		sourceColumn: model

	column roc_auc
		dataType: double
		formatString: 0.000
		lineageTag: c8300005-a91f-4181-8dc7-b5640b2af9c6
		summarizeBy: none
		sourceColumn: roc_auc

	column pr_auc
		dataType: double
		formatString: 0.000
		lineageTag: 899ac91a-6ae8-460c-b7d0-59d191346a0d
		summarizeBy: none
		sourceColumn: pr_auc

	column lift_at_decile
		dataType: double
		formatString: #,0.0
		lineageTag: 7f33c168-00e7-44f1-a67e-d0698da311e0
		summarizeBy: none
		sourceColumn: lift_at_decile

	column is_chosen
		dataType: int64
		formatString: 0
		lineageTag: 212e11e2-be71-4018-8dde-16856ad79ad6
		summarizeBy: none
		sourceColumn: is_chosen

	partition model_evaluation = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\model_evaluation.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"model", type text}, {"roc_auc", type number}, {"pr_auc", type number}, {"lift_at_decile", type number}, {"is_chosen", Int64.Type}})
				in
				    Typed
