table model_evaluation
	lineageTag: dc3d2527-fb58-4870-b7e8-fb1081f4a01f

	column model
		dataType: string
		lineageTag: 4e76fd5b-b4c2-4886-baef-8f9fdfe92e84
		summarizeBy: none
		sourceColumn: model

	column roc_auc
		dataType: double
		lineageTag: 64a9fdbb-371c-47b1-bb20-c125042966c3
		summarizeBy: none
		sourceColumn: roc_auc

	column pr_auc
		dataType: double
		lineageTag: c1519d75-a079-47a1-938e-f40b6c1fbbd3
		summarizeBy: none
		sourceColumn: pr_auc

	column lift_at_decile
		dataType: double
		lineageTag: 9eb85c42-2634-45d3-a3d5-346712f948c5
		summarizeBy: none
		sourceColumn: lift_at_decile

	column is_chosen
		dataType: int64
		formatString: 0
		lineageTag: d0613bd7-ecf9-41c9-9130-abd13c0101ff
		summarizeBy: none
		sourceColumn: is_chosen

	partition model_evaluation = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\model_evaluation.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"model", type text}, {"roc_auc", type number}, {"pr_auc", type number}, {"lift_at_decile", type number}, {"is_chosen", Int64.Type}})
				in
				    Typed
