table pay_equity
	lineageTag: 5f83f7ee-89ee-4501-8fde-dc49b20289f1

	column job_level
		dataType: string
		lineageTag: b054684e-6ea9-4593-8359-ebfdc212ebfe
		summarizeBy: none
		sourceColumn: job_level

	column level_rank
		dataType: int64
		formatString: 0
		lineageTag: 2e1b3f97-8f2a-4a04-a017-67c811a6a2bd
		summarizeBy: none
		sourceColumn: level_rank

	column market_median
		dataType: double
		formatString: \$#,0
		lineageTag: 17cd980b-2c57-415a-a3ba-dc809ec35bc0
		summarizeBy: none
		sourceColumn: market_median

	column n_female
		dataType: int64
		formatString: 0
		lineageTag: fda59be9-8bc4-460e-8ace-b26d11a0d13a
		summarizeBy: sum
		sourceColumn: n_female

	column n_male
		dataType: int64
		formatString: 0
		lineageTag: c53d7736-5f79-47f7-a6c2-0c612a16e6e7
		summarizeBy: sum
		sourceColumn: n_male

	column avg_salary_female
		dataType: double
		formatString: \$#,0
		lineageTag: 56ed5416-c137-4571-a754-94084cfb00cd
		summarizeBy: none
		sourceColumn: avg_salary_female

	column avg_salary_male
		dataType: double
		formatString: \$#,0
		lineageTag: d08c37e5-b7c9-415e-9064-b5f1863bc282
		summarizeBy: none
		sourceColumn: avg_salary_male

	column female_compa_ratio
		dataType: double
		formatString: 0.00
		lineageTag: 50c97fa7-17c8-4926-a0dd-5adf32875a45
		summarizeBy: none
		sourceColumn: female_compa_ratio

	column male_compa_ratio
		dataType: double
		formatString: 0.00
		lineageTag: c1bc8e97-6470-455c-988f-e749e6c320a9
		summarizeBy: none
		sourceColumn: male_compa_ratio

	column raw_gap_pct
		dataType: double
		formatString: 0.0%
		lineageTag: 082889e2-b0cb-4297-b20b-fc8f791687ee
		summarizeBy: none
		sourceColumn: raw_gap_pct

	column gap_flag
		dataType: string
		lineageTag: c32b9de3-697c-48da-90de-c5acc70020f1
		summarizeBy: none
		sourceColumn: gap_flag

	partition pay_equity = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\pay_equity.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"job_level", type text}, {"level_rank", Int64.Type}, {"market_median", type number}, {"n_female", Int64.Type}, {"n_male", Int64.Type}, {"avg_salary_female", type number}, {"avg_salary_male", type number}, {"female_compa_ratio", type number}, {"male_compa_ratio", type number}, {"raw_gap_pct", type number}, {"gap_flag", type text}})
				in
				    Typed

