table pay_equity
	lineageTag: 9705fa87-9ba1-44fc-bf27-4ac966498d72

	column job_level
		dataType: string
		lineageTag: ea4a9c75-c6c2-422a-ba09-c43da2dbc04e
		summarizeBy: none
		sourceColumn: job_level

	column level_rank
		dataType: int64
		formatString: 0
		lineageTag: f5349042-d652-43fb-bcca-c9f96f272a06
		summarizeBy: none
		sourceColumn: level_rank

	column market_median
		dataType: double
		lineageTag: d7dfd86f-5577-4a56-953d-986178a37fc1
		summarizeBy: none
		sourceColumn: market_median

	column n_female
		dataType: int64
		formatString: 0
		lineageTag: 6ea4e20e-25c4-41fc-8407-818bb9e87db3
		summarizeBy: sum
		sourceColumn: n_female

	column n_male
		dataType: int64
		formatString: 0
		lineageTag: 6a5694ff-3df5-4370-b65c-2b03d9f00fb1
		summarizeBy: sum
		sourceColumn: n_male

	column avg_salary_female
		dataType: double
		lineageTag: fcade52a-cc62-4490-8b64-2c0243938a5e
		summarizeBy: none
		sourceColumn: avg_salary_female

	column avg_salary_male
		dataType: double
		lineageTag: 02b902b5-8688-4e3d-bdf0-171a64901853
		summarizeBy: none
		sourceColumn: avg_salary_male

	column female_compa_ratio
		dataType: double
		lineageTag: beaa78bd-f42e-4ed6-a8d7-e5468ada191e
		summarizeBy: none
		sourceColumn: female_compa_ratio

	column male_compa_ratio
		dataType: double
		lineageTag: 4713ff71-b687-4e0f-9894-275a8b6fced7
		summarizeBy: none
		sourceColumn: male_compa_ratio

	column raw_gap_pct
		dataType: double
		lineageTag: 039b1706-310f-4222-aa97-1f8899f5ec5d
		summarizeBy: none
		sourceColumn: raw_gap_pct

	column gap_flag
		dataType: string
		lineageTag: fe2ee887-b7b4-4328-bd4a-ec721e7ef9d1
		summarizeBy: none
		sourceColumn: gap_flag

	partition pay_equity = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\pay_equity.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"job_level", type text}, {"level_rank", Int64.Type}, {"market_median", type number}, {"n_female", Int64.Type}, {"n_male", Int64.Type}, {"avg_salary_female", type number}, {"avg_salary_male", type number}, {"female_compa_ratio", type number}, {"male_compa_ratio", type number}, {"raw_gap_pct", type number}, {"gap_flag", type text}})
				in
				    Typed
