table pay_equity_levels
	lineageTag: 6a9ed081-7315-4937-aafb-18de83e5671b

	column job_level
		dataType: string
		lineageTag: de616f1c-ba17-4e87-a1df-36665ada946f
		summarizeBy: none
		sourceColumn: job_level

	column level_rank
		dataType: int64
		formatString: 0
		lineageTag: fb341f40-656f-4b79-ba3d-ff0d16527ee9
		summarizeBy: none
		sourceColumn: level_rank

	column market_median
		dataType: double
		lineageTag: 044b5217-befb-4fa0-ab0d-deb3662fb975
		summarizeBy: none
		sourceColumn: market_median

	column n_female
		dataType: int64
		formatString: 0
		lineageTag: 85278683-30aa-4c3d-aa60-652d405fe9d3
		summarizeBy: sum
		sourceColumn: n_female

	column n_male
		dataType: int64
		formatString: 0
		lineageTag: c9987d67-b14b-4359-8e72-569029303217
		summarizeBy: sum
		sourceColumn: n_male

	column avg_salary_female
		dataType: double
		lineageTag: c4263681-678e-4447-8a00-272b27eeca89
		summarizeBy: none
		sourceColumn: avg_salary_female

	column avg_salary_male
		dataType: double
		lineageTag: 69310293-16a7-4997-b496-1c2484e0a770
		summarizeBy: none
		sourceColumn: avg_salary_male

	column female_compa_ratio
		dataType: double
		lineageTag: 2479ad01-ae30-455e-94c3-5ee09ac55009
		summarizeBy: none
		sourceColumn: female_compa_ratio

	column male_compa_ratio
		dataType: double
		lineageTag: b1db512f-04dc-4ed3-ab75-43d5d66a74fd
		summarizeBy: none
		sourceColumn: male_compa_ratio

	column raw_gap_pct
		dataType: double
		lineageTag: 85de0aab-57a7-4ed5-8e8b-7f89854ab206
		summarizeBy: none
		sourceColumn: raw_gap_pct

	column gap_flag
		dataType: string
		lineageTag: 8d91ea81-0f90-44bc-94a8-ec382b755b47
		summarizeBy: none
		sourceColumn: gap_flag

	partition pay_equity_levels = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\pay_equity_levels.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"job_level", type text}, {"level_rank", Int64.Type}, {"market_median", type number}, {"n_female", Int64.Type}, {"n_male", Int64.Type}, {"avg_salary_female", type number}, {"avg_salary_male", type number}, {"female_compa_ratio", type number}, {"male_compa_ratio", type number}, {"raw_gap_pct", type number}, {"gap_flag", type text}})
				in
				    Typed
