table pay_equity_levels
	lineageTag: f9b62acd-d3d0-4cec-a92a-6f7af2242cab

	column job_level
		dataType: string
		lineageTag: 00433478-a225-43cc-b639-b84f3bbe45d1
		summarizeBy: none
		sourceColumn: job_level

	column level_rank
		dataType: int64
		formatString: 0
		lineageTag: d2d5878e-5605-4181-a4cd-420cd81c8a32
		summarizeBy: none
		sourceColumn: level_rank

	column market_median
		dataType: double
		formatString: \$#,0
		lineageTag: 93de41fe-82f2-42b5-bc59-633ed3123b65
		summarizeBy: none
		sourceColumn: market_median

	column n_female
		dataType: int64
		formatString: 0
		lineageTag: 23dfb5ce-50d1-439b-8957-6b26896ca1fe
		summarizeBy: sum
		sourceColumn: n_female

	column n_male
		dataType: int64
		formatString: 0
		lineageTag: 0b5327e3-2a80-4e29-8ada-7cb9acd8ec0f
		summarizeBy: sum
		sourceColumn: n_male

	column avg_salary_female
		dataType: double
		formatString: \$#,0
		lineageTag: e4900655-c93f-4b94-8db9-af1d9839a678
		summarizeBy: none
		sourceColumn: avg_salary_female

	column avg_salary_male
		dataType: double
		formatString: \$#,0
		lineageTag: 72d585d5-b013-44a9-a701-174fbb1570c5
		summarizeBy: none
		sourceColumn: avg_salary_male

	column female_compa_ratio
		dataType: double
		formatString: 0.00
		lineageTag: 5ae6d00b-7134-4cd2-bfe0-9c768764e197
		summarizeBy: none
		sourceColumn: female_compa_ratio

	column male_compa_ratio
		dataType: double
		formatString: 0.00
		lineageTag: 6265e3c6-6bc9-41e6-98d9-43e10226e639
		summarizeBy: none
		sourceColumn: male_compa_ratio

	column raw_gap_pct
		dataType: double
		formatString: 0.0%
		lineageTag: 3267b02b-f24c-4a46-9fec-67970afb1c78
		summarizeBy: none
		sourceColumn: raw_gap_pct

	column gap_flag
		dataType: string
		lineageTag: 6c47b017-72ac-4a79-b2f9-0a9df96fe229
		summarizeBy: none
		sourceColumn: gap_flag

	partition pay_equity_levels = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\pay_equity_levels.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"job_level", type text}, {"level_rank", Int64.Type}, {"market_median", type number}, {"n_female", Int64.Type}, {"n_male", Int64.Type}, {"avg_salary_female", type number}, {"avg_salary_male", type number}, {"female_compa_ratio", type number}, {"male_compa_ratio", type number}, {"raw_gap_pct", type number}, {"gap_flag", type text}})
				in
				    Typed
