table recruiting_kpis
	lineageTag: f6c50c0a-2713-4dd5-995e-3a016c4b8822

	column total_applications
		dataType: int64
		formatString: 0
		lineageTag: 1fdde486-8a9f-48ff-b422-13344fc112ae
		summarizeBy: none
		sourceColumn: total_applications

	column total_hires
		dataType: int64
		formatString: 0
		lineageTag: 0b80c62b-96b4-4508-a6fc-7c200fc5523c
		summarizeBy: none
		sourceColumn: total_hires

	column overall_hire_rate
		dataType: double
		lineageTag: 50e71f46-4069-488a-93e8-32ce1ba54683
		summarizeBy: none
		sourceColumn: overall_hire_rate

	column offer_accept_rate
		dataType: double
		lineageTag: 4ce6e07e-4f29-4986-8867-f8ccaf62ca86
		summarizeBy: none
		sourceColumn: offer_accept_rate

	column median_days_to_fill
		dataType: double
		lineageTag: 241af3f2-f3e7-4250-99fd-a0f2c1f1b639
		summarizeBy: none
		sourceColumn: median_days_to_fill

	column avg_days_to_fill
		dataType: double
		lineageTag: e043a66e-1db6-4a67-9641-7a07a1fe7c3a
		summarizeBy: none
		sourceColumn: avg_days_to_fill

	partition recruiting_kpis = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\recruiting_kpis.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"total_applications", Int64.Type}, {"total_hires", Int64.Type}, {"overall_hire_rate", type number}, {"offer_accept_rate", type number}, {"median_days_to_fill", type number}, {"avg_days_to_fill", type number}})
				in
				    Typed
