table recruiting_by_source
	lineageTag: b1557ab5-d908-48d7-b68d-1069ee9bb983

	column source
		dataType: string
		lineageTag: 02183536-f881-4b96-af17-7458d1795603
		summarizeBy: none
		sourceColumn: source

	column applications
		dataType: int64
		formatString: 0
		lineageTag: abd649fe-8af4-4043-8cb3-2dc5c46b997d
		summarizeBy: sum
		sourceColumn: applications

	column offers
		dataType: int64
		formatString: 0
		lineageTag: e01a04f8-9500-450e-8410-fe4e4b264ec5
		summarizeBy: sum
		sourceColumn: offers

	column hires
		dataType: int64
		formatString: 0
		lineageTag: 72e4a63c-6d43-4146-b115-0370efd95129
		summarizeBy: sum
		sourceColumn: hires

	column hire_rate
		dataType: double
		lineageTag: cd4a1999-e114-431b-ac23-4d396454a5ac
		summarizeBy: none
		sourceColumn: hire_rate

	column offer_accept_rate
		dataType: double
		lineageTag: 6b792601-f355-4697-9487-80d1916cef2d
		summarizeBy: none
		sourceColumn: offer_accept_rate

	column avg_days_to_fill
		dataType: double
		lineageTag: 8f13aa01-a247-47a6-abc7-df05b914059c
		summarizeBy: none
		sourceColumn: avg_days_to_fill

	column hire_rate_rank
		dataType: int64
		formatString: 0
		lineageTag: 9f48c2e6-c07a-42c1-95fa-150cc2460609
		summarizeBy: none
		sourceColumn: hire_rate_rank

	partition recruiting_by_source = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\recruiting_by_source.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"source", type text}, {"applications", Int64.Type}, {"offers", Int64.Type}, {"hires", Int64.Type}, {"hire_rate", type number}, {"offer_accept_rate", type number}, {"avg_days_to_fill", type number}, {"hire_rate_rank", Int64.Type}})
				in
				    Typed
