table recruiting_kpis
	lineageTag: 980e86d7-1b74-4b8b-b084-092f4bcca225

	column total_applications
		dataType: int64
		formatString: 0
		lineageTag: 2859bdb1-2c15-4328-a7d4-19382bec209a
		summarizeBy: none
		sourceColumn: total_applications

	column total_hires
		dataType: int64
		formatString: 0
		lineageTag: 7ff2f392-4e2a-40f3-9399-24cac97ecc43
		summarizeBy: none
		sourceColumn: total_hires

	column overall_hire_rate
		dataType: double
		formatString: 0.0%
		lineageTag: 19fe82e1-d06b-4851-8eb1-bbe9ad5ae4f5
		summarizeBy: none
		sourceColumn: overall_hire_rate

	column offer_accept_rate
		dataType: double
		formatString: 0.0%
		lineageTag: b825711e-11b0-4466-a99c-07a3124d6fcb
		summarizeBy: none
		sourceColumn: offer_accept_rate

	column median_days_to_fill
		dataType: double
		formatString: #,0.0
		lineageTag: 20690bb7-9bb7-4485-b1c9-d58ac64dd538
		summarizeBy: none
		sourceColumn: median_days_to_fill

	column avg_days_to_fill
		dataType: double
		formatString: #,0.0
		lineageTag: a9575bae-b623-4c4d-8355-1490f5dca87b
		summarizeBy: none
		sourceColumn: avg_days_to_fill

	partition recruiting_kpis = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\recruiting_kpis.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"total_applications", Int64.Type}, {"total_hires", Int64.Type}, {"overall_hire_rate", type number}, {"offer_accept_rate", type number}, {"median_days_to_fill", type number}, {"avg_days_to_fill", type number}})
				in
				    Typed
