table recruiting_by_source
	lineageTag: 7166119c-cab6-4660-ae74-f1d7d05c8631

	column source
		dataType: string
		lineageTag: ff50929d-566d-4bce-937a-298617751f13
		summarizeBy: none
		sourceColumn: source

	column applications
		dataType: int64
		formatString: 0
		lineageTag: b83aa66a-3872-4c3e-9a35-059de639861f
		summarizeBy: sum
		sourceColumn: applications

	column offers
		dataType: int64
		formatString: 0
		lineageTag: c80ddcf4-1a36-4657-b677-70428f16b07c
		summarizeBy: sum
		sourceColumn: offers

	column hires
		dataType: int64
		formatString: 0
		lineageTag: dea6f966-661c-4405-9489-799ecf4e486f
		summarizeBy: sum
		sourceColumn: hires

	column hire_rate
		dataType: double
		formatString: 0.0%
		lineageTag: 7ef60f00-3ac1-4a93-8142-e0794935a7a9
		summarizeBy: none
		sourceColumn: hire_rate

	column offer_accept_rate
		dataType: double
		formatString: 0.0%
		lineageTag: dc4f12ff-cb7c-48b8-86a1-bc68070bebb5
		summarizeBy: none
		sourceColumn: offer_accept_rate

	column avg_days_to_fill
		dataType: double
		formatString: #,0.0
		lineageTag: 63891197-3c7e-4e4c-b72e-f22362e3d993
		summarizeBy: none
		sourceColumn: avg_days_to_fill

	column hire_rate_rank
		dataType: int64
		formatString: 0
		lineageTag: b9c5d6c0-fcf6-4745-afbc-1effc794b71c
		summarizeBy: none
		sourceColumn: hire_rate_rank

	partition recruiting_by_source = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\recruiting_by_source.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"source", type text}, {"applications", Int64.Type}, {"offers", Int64.Type}, {"hires", Int64.Type}, {"hire_rate", type number}, {"offer_accept_rate", type number}, {"avg_days_to_fill", type number}, {"hire_rate_rank", Int64.Type}})
				in
				    Typed

