table retention_cohorts
	lineageTag: fcf11065-fd99-41c5-bc3e-4987c510f62c

	column cohort_year
		dataType: string
		lineageTag: fd5b4bc8-9da3-4ea6-bbfe-d7a3710de946
		summarizeBy: none
		sourceColumn: cohort_year
		sortByColumn: cohort_sort

	column cohort_sort
		dataType: int64
		formatString: 0
		lineageTag: a35a713a-4011-48d4-a333-2eb39cbf864d
		summarizeBy: none
		sourceColumn: cohort_sort

	column months_since_hire
		dataType: int64
		formatString: 0
		lineageTag: 129f5571-0e01-4734-ae78-805acf949d59
		summarizeBy: none
		sourceColumn: months_since_hire

	column eligible
		dataType: int64
		formatString: 0
		lineageTag: d0984189-9e33-4128-9b31-0ccc78794a95
		summarizeBy: sum
		sourceColumn: eligible

	column retained
		dataType: int64
		formatString: 0
		lineageTag: 16da4537-b5ee-4050-86e2-57e95840aee3
		summarizeBy: sum
		sourceColumn: retained

	column retention_rate
		dataType: double
		lineageTag: 49da3998-416c-453b-a94a-fa94f99ac381
		summarizeBy: none
		sourceColumn: retention_rate

	column retention_delta
		dataType: double
		lineageTag: 1b22e2e1-6ab0-4266-81c5-d65120fcea8f
		summarizeBy: none
		sourceColumn: retention_delta

	partition retention_cohorts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\retention_cohorts.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"cohort_year", type text}, {"cohort_sort", Int64.Type}, {"months_since_hire", Int64.Type}, {"eligible", Int64.Type}, {"retained", Int64.Type}, {"retention_rate", type number}, {"retention_delta", type number}})
				in
				    Typed
