table retention_cohorts
	lineageTag: 76fb9f45-3ff8-4ce4-99a4-04e4beec4391

	column cohort_year
		dataType: string
		lineageTag: 72a01997-979b-4c1f-9468-02c6d17af5b5
		summarizeBy: none
		sourceColumn: cohort_year
		sortByColumn: cohort_sort

	column cohort_sort
		dataType: int64
		formatString: 0
		lineageTag: b2db3e38-e635-42a6-a4dd-7319315946f4
		summarizeBy: none
		sourceColumn: cohort_sort

	column months_since_hire
		dataType: int64
		formatString: 0
		lineageTag: 59652af7-2a35-482f-aa06-2df68500c7d2
		summarizeBy: none
		sourceColumn: months_since_hire

	column eligible
		dataType: int64
		formatString: 0
		lineageTag: d5cf983b-3404-4f43-af69-7b9a0763984a
		summarizeBy: sum
		sourceColumn: eligible

	column retained
		dataType: int64
		formatString: 0
		lineageTag: 019ae2e8-f996-4ecc-9f9c-2d5cd31b5764
		summarizeBy: sum
		sourceColumn: retained

	column retention_rate
		dataType: double
		formatString: 0.0%
		lineageTag: 1f43062d-0792-48a0-b00d-69c9186ddc22
		summarizeBy: none
		sourceColumn: retention_rate

	column retention_delta
		dataType: double
		formatString: 0.0%
		lineageTag: 5a1bf236-da06-4d0c-a4bc-4ed30b8e238a
		summarizeBy: none
		sourceColumn: retention_delta

	partition retention_cohorts = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\retention_cohorts.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"cohort_year", type text}, {"cohort_sort", Int64.Type}, {"months_since_hire", Int64.Type}, {"eligible", Int64.Type}, {"retained", Int64.Type}, {"retention_rate", type number}, {"retention_delta", type number}})
				in
				    Typed

