table workforce_kpis
	lineageTag: 861bae61-75e5-4e35-82d0-9ba5fa3f7034

	column month
		dataType: string
		lineageTag: 533ea486-effe-408a-a9f0-ad3208a613d2
		summarizeBy: none
		sourceColumn: month

	column headcount
		dataType: int64
		formatString: 0
		lineageTag: ad0c7305-a24b-4541-afe2-b3a521649661
		summarizeBy: sum
		sourceColumn: headcount

	column hires
		dataType: int64
		formatString: 0
		lineageTag: ba603e30-7357-4823-8db5-295fc48dc0ed
		summarizeBy: sum
		sourceColumn: hires

	column terminations
		dataType: int64
		formatString: 0
		lineageTag: bb2f0076-3506-4322-aa0c-d09ba81ae612
		summarizeBy: sum
		sourceColumn: terminations

	column voluntary_terms
		dataType: int64
		formatString: 0
		lineageTag: 96c48ab4-cce9-4e09-8f93-e958c18e2dab
		summarizeBy: sum
		sourceColumn: voluntary_terms

	column involuntary_terms
		dataType: int64
		formatString: 0
		lineageTag: d81e4816-c543-402d-9fb9-eae19b41ce1c
		summarizeBy: sum
		sourceColumn: involuntary_terms

	column monthly_turnover_rate
		dataType: double
		lineageTag: bb7c120d-e2da-43f0-8e09-8a6b4cb137e5
		summarizeBy: none
		sourceColumn: monthly_turnover_rate

	column rolling_12m_terms
		dataType: int64
		formatString: 0
		lineageTag: a4636bc5-e6b7-4cc5-b94d-126e610d7ba5
		summarizeBy: sum
		sourceColumn: rolling_12m_terms

	column rolling_12m_avg_headcount
		dataType: double
		lineageTag: 7062f70c-e413-4725-920b-a84b9c6a4345
		summarizeBy: none
		sourceColumn: rolling_12m_avg_headcount

	column rolling_12m_attrition_rate
		dataType: double
		lineageTag: 7367fbba-4de4-4f66-9c2b-d6320d7fca74
		summarizeBy: none
		sourceColumn: rolling_12m_attrition_rate

	partition workforce_kpis = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\workforce_kpis.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"month", type text}, {"headcount", Int64.Type}, {"hires", Int64.Type}, {"terminations", Int64.Type}, {"voluntary_terms", Int64.Type}, {"involuntary_terms", Int64.Type}, {"monthly_turnover_rate", type number}, {"rolling_12m_terms", Int64.Type}, {"rolling_12m_avg_headcount", type number}, {"rolling_12m_attrition_rate", type number}})
				in
				    Typed
