table workforce_kpis
	lineageTag: 62fbfb8b-ae43-4000-b3ff-5b1cf4fc4fe5

	column month
		dataType: string
		lineageTag: e1bfe0bc-288c-49bf-966e-6d89f0a3a6f3
		summarizeBy: none
		sourceColumn: month

	column headcount
		dataType: int64
		formatString: 0
		lineageTag: 01f91d07-7ed2-4ea7-9cd6-27ca72e5409d
		summarizeBy: sum
		sourceColumn: headcount

	column hires
		dataType: int64
		formatString: 0
		lineageTag: a154a567-2239-4135-a64f-5af3a519add5
		summarizeBy: sum
		sourceColumn: hires

	column terminations
		dataType: int64
		formatString: 0
		lineageTag: 3c33ff37-09a4-45ba-a838-5389096477f4
		summarizeBy: sum
		sourceColumn: terminations

	column voluntary_terms
		dataType: int64
		formatString: 0
		lineageTag: 0ad2efae-2b3a-43ca-ae81-59303e1957b4
		summarizeBy: sum
		sourceColumn: voluntary_terms

	column involuntary_terms
		dataType: int64
		formatString: 0
		lineageTag: 177ae0e1-e76b-4318-afa1-ed7bb1fe3acd
		summarizeBy: sum
		sourceColumn: involuntary_terms

	column monthly_turnover_rate
		dataType: double
		formatString: 0.0%
		lineageTag: a0c91489-9e24-41e3-bca9-f993ea02c3ea
		summarizeBy: none
		sourceColumn: monthly_turnover_rate

	column rolling_12m_terms
		dataType: int64
		formatString: 0
		lineageTag: 096784f9-edef-4fa1-b06e-5f811ec89c85
		summarizeBy: sum
		sourceColumn: rolling_12m_terms

	column rolling_12m_avg_headcount
		dataType: double
		formatString: #,0.0
		lineageTag: 08c16f92-5d9c-4b0f-a1a1-79773a59eaa0
		summarizeBy: none
		sourceColumn: rolling_12m_avg_headcount

	column rolling_12m_attrition_rate
		dataType: double
		formatString: 0.0%
		lineageTag: a340dd6d-b867-44f9-8072-5c2db5b0f5a6
		summarizeBy: none
		sourceColumn: rolling_12m_attrition_rate

	partition workforce_kpis = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\workforce_kpis.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"month", type text}, {"headcount", Int64.Type}, {"hires", Int64.Type}, {"terminations", Int64.Type}, {"voluntary_terms", Int64.Type}, {"involuntary_terms", Int64.Type}, {"monthly_turnover_rate", type number}, {"rolling_12m_terms", Int64.Type}, {"rolling_12m_avg_headcount", type number}, {"rolling_12m_attrition_rate", type number}})
				in
				    Typed

