table workforce_kpis
	lineageTag: 41f3e812-93a5-4854-8ad0-6df471d29d13

	column month
		dataType: string
		lineageTag: 46326b71-b2cc-4a4a-84db-fffeebbe9acb
		summarizeBy: none
		sourceColumn: month

	column headcount
		dataType: int64
		formatString: 0
		lineageTag: 6075603a-92c2-42ca-8771-5eddb5204829
		summarizeBy: sum
		sourceColumn: headcount

	column hires
		dataType: int64
		formatString: 0
		lineageTag: bbae7663-a189-49b7-b055-78867a33bb28
		summarizeBy: sum
		sourceColumn: hires

	column terminations
		dataType: int64
		formatString: 0
		lineageTag: 8073a35d-a945-4982-9d3c-c81a96ae1b94
		summarizeBy: sum
		sourceColumn: terminations

	column voluntary_terms
		dataType: int64
		formatString: 0
		lineageTag: 59f2c8c9-19c7-426d-b3d6-d45843be4816
		summarizeBy: sum
		sourceColumn: voluntary_terms

	column involuntary_terms
		dataType: int64
		formatString: 0
		lineageTag: 50e0b9d5-4cea-4ba8-8df0-b48524ec16e4
		summarizeBy: sum
		sourceColumn: involuntary_terms

	column monthly_turnover_rate
		dataType: double
		lineageTag: 6449d0bf-b314-439e-9f61-34b2d78dd263
		summarizeBy: none
		sourceColumn: monthly_turnover_rate

	column rolling_12m_terms
		dataType: int64
		formatString: 0
		lineageTag: 3a4292a1-d256-4f74-8750-6946705f776a
		summarizeBy: sum
		sourceColumn: rolling_12m_terms

	column rolling_12m_avg_headcount
		dataType: double
		lineageTag: a0ca90c2-8c8c-4601-93ee-c435aab4f27c
		summarizeBy: none
		sourceColumn: rolling_12m_avg_headcount

	column rolling_12m_attrition_rate
		dataType: double
		lineageTag: 2ccd3d2f-2f51-4468-be9f-1c5ca9637e7c
		summarizeBy: none
		sourceColumn: rolling_12m_attrition_rate

	partition workforce_kpis = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\output\workforce_kpis.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"month", type text}, {"headcount", Int64.Type}, {"hires", Int64.Type}, {"terminations", Int64.Type}, {"voluntary_terms", Int64.Type}, {"involuntary_terms", Int64.Type}, {"monthly_turnover_rate", type number}, {"rolling_12m_terms", Int64.Type}, {"rolling_12m_avg_headcount", type number}, {"rolling_12m_attrition_rate", type number}})
				in
				    Typed
